export enum NotificationType {
  AFFILIATION_REQUEST = "AFFILIATION_REQUEST",
  AFFILIATION_REQUEST_APPROVED = "AFFILIATION_REQUEST_APPROVED",
  AFFILIATION_REQUEST_REJECTED = "AFFILIATION_REQUEST_REJECTED",
  SYSTEM = "SYSTEM",
  FROM_STABLE = "FROM_STABLE",
  SUCCESS = "SUCCESS",
  INFO = "INFO",
  VALIDATION = "VALIDATION",
}
